%YAML 1.2
---
method:
  description: Dakota analysis method
  value:
    type: choice
    default: "vector parameter study"
    choices:
      - "vector parameter study"
      - "centered parameter study"
---
component_parameters:
  name: Component parameters
  description: null
  value:
    type: dynamic_choice
    default: null
---
response_metrics:
  name: Response metrics
  description: null
  value:
    type: dynamic_choice
    default: null
