language: python
python:
  - "2.7"

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - pip install -r requirements.txt
  - pip install coveralls

install:
  - python setup.py install

script:
  - nosetests --with-doctest --with-coverage --cover-package=csdms.dakota

after_success:
  - coveralls
