language: python

python:
  - "2.7"

os:
  - linux

install:
  - sudo apt-get update -qq
  - sudo apt-get install python-scipy
  - pip install -r requirements.txt
  - python setup.py install

script:
  - nosetests --with-doctest
