language: python

python:
  - "2.7"

os:
  - linux

install:
  - sudo apt-get update -qq
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install

script:
  - nosetests --with-doctest
