descriptor1:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
initial_point1:
  description: Start point (center value) for study variable
  value:
    type: float
    default: 0.0
    units: '-'
steps_per_variable1:
  description: Number of steps to take in each direction
  value:
    type: int
    default: 1
    range:
      min: 1
      max: 100
    units: '-'
step_vector1:
  description: Step size in each direction
  value:
    type: float
    default: 1.0
    range:
      min: 1e-6
      max: 1e+6
    units: '-'
descriptor2:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
initial_point2:
  description: Start point (center value) for study variable
  value:
    type: float
    default: 0.0
    units: '-'
steps_per_variable2:
  description: Number of steps to take in each direction
  value:
    type: int
    default: 1
    range:
      min: 1
      max: 100
    units: '-'
step_vector2:
  description: Step size in each direction
  value:
    type: float
    default: 1.0
    range:
      min: 1e-6
      max: 1e+6
    units: '-'
descriptor3:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
initial_point3:
  description: Start point (center value) for study variable
  value:
    type: float
    default: 0.0
    units: '-'
steps_per_variable3:
  description: Number of steps to take in each direction
  value:
    type: int
    default: 1
    range:
      min: 1
      max: 100
    units: '-'
step_vector3:
  description: Step size in each direction
  value:
    type: float
    default: 1.0
    range:
      min: 1e-6
      max: 1e+6
    units: '-'
response_descriptor1:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic1:
  description: Statistic computed on response
  value:
    type: choice
    default: Mean
    choices:
      - Mean
      - Median
      - Sum
      - Standard deviation
      - Maximum
      - Minimum
    units: '-'
response_descriptor2:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic2:
  description: Statistic computed on response
  value:
    type: choice
    default: Mean
    choices:
      - Mean
      - Median
      - Sum
      - Standard deviation
      - Maximum
      - Minimum
    units: '-'
response_descriptor3:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic3:
  description: Statistic computed on response
  value:
    type: choice
    default: Mean
    choices:
      - Mean
      - Median
      - Sum
      - Standard deviation
      - Maximum
      - Minimum
    units: '-'
