package:
  name: dakotathon
  version: {{"0.3.1" + environ.get('BUILD_STR', '')}}

source:
  path: ..

requirements:
  build:
    - python
    - numpy
    - pyyaml
    - basic-modeling-interface
    - nose
  run:
    - python
    - numpy
    - pyyaml
    - basic-modeling-interface
    - nose
