component:
  description: Name of CSDMS component
  value:
    type: string
    default:
plugin:
  description: Name of model plugin
  value:
    type: string
    default:
run_directory:
  description: Directory in which Dakota experiment is run
  value:
    type: string
    default: '.'
template_file:
  description: Dakota template of model configuration file
  value:
    type: string
    default: 'dakota.yaml.dtmpl'
auxiliary_files:
  description: Additional model input files
  value:
    type: list
    default: []
analysis_driver:
  description: Dakota analysis driver program
  value:
    type: choice
    default: dakota_run_plugin
    choices:
      - dakota_run_plugin
      - dakota_run_component
id_interface:
  description: Name of the interface block
  value:
    type: string
    default: CSDMS
initialize_args:
  description: Arguments passed to component initialize method
  value:
    type: string
    default: ''

descriptors:
  description: Input variable name
  value:
    type: list
    default: []
lower_bounds:
  description: Lower bound on values of study variable
  value:
    type: float
    default: [0.0]
upper_bounds:
  description: Upper bound on values of study variable
  value:
    type: list
    default: [1.0]
partitions:
  description: Number of partitions between lower and upper bounds
  value:
    type: list
    default: [2]
response_descriptors:
  description: Response variable name
  value:
    type: list
    default: []
response_statistics:
  description: Statistic computed on response
  value:
    type: list
    default: ['mean']
response_files:
  description: Model output files used for calculating response
  value:
    type: list
    default: []
