descriptor1:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
lower_bound1:
  description: Lower bound on values of study variable
  value:
    type: float
    default: 0.0
    range:
      min: -1e6
      max: 1e6
    units: '-'
upper_bound1:
  description: Upper bound on values of study variable
  value:
    type: float
    default: 1.0
    range:
      min: -1e6
      max: 1e6
    units: '-'
partition1:
  description: Number of partitions between lower and upper bounds
  value:
    type: int
    default: 2
    range:
      min: 1
      max: 1e2
    units: '-'
descriptor2:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
lower_bound2:
  description: Lower bound on values of study variable
  value:
    type: float
    default: 0.0
    range:
      min: -1e6
      max: 1e6
    units: '-'
upper_bound2:
  description: Upper bound on values of study variable
  value:
    type: float
    default: 1.0
    range:
      min: -1e6
      max: 1e6
    units: '-'
partition2:
  description: Number of partitions between lower and upper bounds
  value:
    type: int
    default: 1
    range:
      min: 2
      max: 1e2
    units: '-'
descriptor3:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
lower_bound3:
  description: Lower bound on values of study variable
  value:
    type: float
    default: 0.0
    range:
      min: -1e6
      max: 1e6
    units: '-'
upper_bound3:
  description: Upper bound on values of study variable
  value:
    type: float
    default: 1.0
    range:
      min: -1e6
      max: 1e6
    units: '-'
partition3:
  description: Number of partitions between lower and upper bounds
  value:
    type: int
    default: 1
    range:
      min: 2
      max: 1e2
    units: '-'
response_descriptor1:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic1:
  description: Statistic computed on response
  value:
    type: choice
    default: mean
    choices:
      - mean
      - median
      - sum
      - std
      - max
      - min
    units: '-'
response_descriptor2:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic2:
  description: Statistic computed on response
  value:
    type: choice
    default: mean
    choices:
      - mean
      - median
      - sum
      - std
      - max
      - min
    units: '-'
response_descriptor3:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic3:
  description: Statistic computed on response
  value:
    type: choice
    default: mean
    choices:
      - mean
      - median
      - sum
      - std
      - max
      - min
    units: '-'
