descriptor1:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
initial_point1:
  description: Start point for study variable
  value:
    type: float
    default: 0.0
    units: '-'
final_point1:
  description: End point for study variable
  value:
    type: float
    default: 1.0
    units: '-'
descriptor2:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
initial_point2:
  description: Start point for study variable
  value:
    type: float
    default: 0.0
    units: '-'
final_point2:
  description: End point for study variable
  value:
    type: float
    default: 1.0
    units: '-'
descriptor3:
  description: Input variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
initial_point3:
  description: Start point for study variable
  value:
    type: float
    default: 0.0
    units: '-'
final_point3:
  description: End point for study variable
  value:
    type: float
    default: 1.0
    units: '-'
n_steps:
  description: Number of steps to take along vector
  value:
    type: int
    default: 4
    range:
      min: 1
      max: 1e3
    units: '-'
response_descriptor1:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic1:
  description: Statistic computed on response
  value:
    type: choice
    default: mean
    choices:
      - mean
      - median
      - sum
      - std
      - max
      - min
    units: '-'
response_descriptor2:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic2:
  description: Statistic computed on response
  value:
    type: choice
    default: mean
    choices:
      - mean
      - median
      - sum
      - std
      - max
      - min
    units: '-'
response_descriptor3:
  description: Response variable name
  value:
    type: dynamic_choice
    default:
    units: '-'
response_statistic3:
  description: Statistic computed on response
  value:
    type: choice
    default: mean
    choices:
      - mean
      - median
      - sum
      - std
      - max
      - min
    units: '-'
