component:
  description: Name of CSDMS component
  value:
    type: string
    default:
plugin:
  description: Name of model plugin
  value:
    type: string
    default:
template_file:
  description: Dakota template of model configuration file
  value:
    type: string
    default: 'config.yaml.dtmpl'
auxiliary_files:
  description: Additional model input files
  value:
    type: list
    default: []
analysis_driver:
  description: Dakota analysis driver program
  value:
    type: choice
    default: dakota_run_plugin
    choices:
      - dakota_run_plugin
      - dakota_run_component
id_interface:
  description: Name of the interface block
  value:
    type: string
    default: CSDMS

descriptors:
  description: Input variable name
  value:
    type: list
    default: []
initial_point:
  description: Start point for study variable
  value:
    type: list
    default: [0.0]
final_point:
  description: End point for study variable
  value:
    type: list
    default: [1.0]
n_steps:
  description: Number of steps to take along vector
  value:
    type: int
    default: 5
    range:
      min: 1
      max: 1e3
response_descriptors:
  description: Response variable name
  value:
    type: list
    default: []
response_statistics:
  description: Statistic computed on response
  value:
    type: list
    default: ['mean']
response_files:
  description: Model output files used for calculating response
  value:
    type: list
    default: []
